### ISSUE TITLE
CORS Issue - Unable to Access API from Web Applications

### ISSUE THREAD

**Issue by ColtoiAndrei** [backdevs/romanian-bank-holidays-api#54]
Hi,

I'm encountering a CORS issue when trying to access the API (https://api.bank-holidays.ro) from a web application. The browser blocks the request due to the absence of Access-Control-Allow-Origin headers in the API response.

Could you please enable CORS on the server to allow requests from any web applications? This would greatly help in integrating the API with front-end projects.

Thank you!

**Comment by bogdannbv** [comment]
Hi @ColtoiAndrei, thanks for your suggestion, unfortunately I won't be enabling `CORS`.

Enabling `CORS` for `"*"` would mean that anyone could use the API directly in their front-end apps which will result in:
- an exponential increase in traffic that the API would have to handle
- increased deployment complexity

In the end both of these will result in an increased cost of operation.

Besides that, having your front-end rely on a 3rd party API, IMO, is a bad idea as the API could go down at any point resulting in a bad experience for your end users.

What I suggest is you implement a mechanism in your back-end that fetches the holidays regularly (e.g.: once a week, once a month, etc.) and caches them and an endpoint that servers them from cache.
This way you'll be sure that the holidays will be served correctly and won't rely on a 3rd party API to be up and running.

Another option would be to spin-up your own instance using the [Docker image](https://hub.docker.com/r/backdevs/romanian-bank-holidays-api) of this API and use that in your front-end:

Example `docker-compose.yml`:
```yml
services:
    bank-holidays-api:
        image: backdevs/romanian-bank-holidays-api:1.3.2
        restart: always
        ports:
            - "8080:8080"
```
